### ISSUE TITLE
Road to v1.8

### ISSUE THREAD

**Issue by nowsprinting** [DeNA/Anjin#100]
### Features

- [x] #92 and other fixes and refactors
- [x] #95
- [x] #97
- [x] #98
- [x] #103 
- [x] #105 
- [x] #106 
- [x] #108 
- [x] #115 

### Tests

- [x] Integration tests (migration, etc.)

**Comment by bo40** [comment]
@nowsprinting san
All of the features above have been successfully merged.
I'd like to confirm if it's OK to release Anjin v1.8 at this time.

**Comment by nowsprinting** [comment]
@bo40 san,
Thank you for your reply.
I hope v1.8 will be release after merges #116 and #117 .

**Comment by bo40** [comment]
Understood. I will review those PRs.

**Comment by nowsprinting** [comment]
@bo40 san, I'm going to post a few PRs today. Sorry...

**Comment by nowsprinting** [comment]
🚀

**Comment by bo40** [comment]
released v1.8.0 in #121
