### ISSUE TITLE
[Error] cannot convert from 'DeNA.Anjin.Reporters.SlackReporter.CoroutineRunner' to 'System.Threading.CancellationToken'

### ISSUE THREAD

**Issue by rosiro** [DeNA/Anjin#7]
I installed anjin from packagemanager.
Version 1.0.1 - March 31, 2023
After installation, I get the following error message

[Error] Argument 1:
Cannot convert from 'DeNA.Anjin.Reporters.SlackReporter.CoroutineRunner' to 'System.Threading.CancellationToken'

https://github.com/DeNA/Anjin/blob/c2f6415d33c8bb791e6465f41790809f2ce8822f/Runtime/Reporters/SlackReporter.cs#L66

The version of unity is 2020.3.43.
The test framework is Version 1.1.33.

**Comment by nowsprinting** [comment]
Check the version of UniTask (com.cysharp.unitask) installed.
You can tell by looking at package-lock.json.

`UniTask.WaitForEndOfFrame(MonoBehaviour)` was implemented in UniTask v2.3.1.

**Comment by rosiro** [comment]
Thanks for your reply.
I installed UniTask, but the error still occurs.
(Unitask has re-installed 2.3.1.)
manifest.json
```
"dependencies": {
    "com.cysharp.unitask": "https://github.com/Cysharp/UniTask.git?path=src/UniTask/Assets/Plugins/UniTask#2.3.1",
```

Here is the error as it appears in the unity console log
```

[CompilerError] Argument 1:.
Cannot convert from 'DeNA.Anjin.Reporters.SlackReporter.CoroutineRunner' to 'System.Threading.CancellationToken'
Compiler Error at Library\PackageCache\com.dena.anjin@1.0.1\Runtime\Reporters\SlackReporter.cs:66 column 53


```

**Comment by rosiro** [comment]
reopen

**Comment by nowsprinting** [comment]
This compile error occurs when using UniTask v2.3.0 or older.

Do you have an older version of UniTask directly within your project?
Look at the package-lock.json file, not manifest.json.
If there is an embedded package, that will take precedence.
Or maybe placed directly under the Assets directory.

**Comment by nowsprinting** [comment]
Or use the IDE's code jump to see where the `UniTask.WaitForEndOfFrame` source is located.

**Comment by rosiro** [comment]
Sorry for the late reply.
I reinstalled UniTask here (UniTask 2.3.3).
I had UniTask 2.3.3 installed when I asked the question in the Issue.
It seems that either there was no UniTask 2.3.3 or I made a mistake in checking.
Thank you very much.

**Comment by nowsprinting** [comment]
I'm glad you seem to have solved it!
I'll add this case to the troubleshooting documentation.
