### ISSUE TITLE
Ask: Can I change keywords in Japanese transration?

### ISSUE THREAD

**Issue by nowsprinting** [DeNA/Anjin#84]
The following words are keywords, so I want to leave them as English words (same as `Agent`):

- Logger (now; ロガー)
- Reporter (now; レポータ)

Target: README_ja.md, Editor/Localization/ja.po

**Comment by nowsprinting** [comment]
Can I proceed with this?
@Kuniwak san, @get-me-power san, @bo40 san, @asurato san

**Comment by get-me-power** [comment]
@nowsprinting 

Yes, please proceed.
